# This workflow uses 2 native nodes (amd/64 and arm/64), Docker's Buildx to build multi-architecture images simultaneously.
# Runner is hosted on AMD node. 

name: Native multi-architecture Buildx

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Upgrade NPM packages weekly"]
    types: [completed]


jobs:
  docker:
    if: $ {{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:

      - uses: docker/login-action@v3.7.0
        with:
          username: $ {{ vars.DOCKERHUB_USERNAME }}
          password: $ {{ secrets.DOCKERHUB_TOKEN }}


    # Checks out code
      - uses: actions/checkout@v6.0.2

    # Sets up SSH agent so runner can talk to ARM node
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: $ {{ secrets.SSH_GH_KEY }}

      - uses: docker/setup-buildx-action@v3.12.0
        with:
          driver: docker-container
          endpoint: unix:///var/run/docker.sock
          platforms: linux/amd64
          append: |
            endpoint: ssh://rizky@100.125.121.96
            platforms: linux/arm64

      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: user/app:date
          cache-binary: true
