# This workflow will update packages in package.json using npx, run test scripts (if present) and create a pull request if tests passed. 
# Written with help from Gemini, Peter Evans' example and Michael Currin's.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Upgrade NPM packages weekly

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly rebuild (Sunday at midnight)
  workflow_dispatch:
    
permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.3.1
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '24.x'
        cache: 'npm'
    - run: npm ci
    - run: npm test --if-present
    - run: npm run build --if-present
    
  upgrade-packages:

    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    needs: build

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.3.1

    - name: Setup Node.js environment
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with: 
        node-version: '24.x'
        cache: npm

    - name: Update dependencies
      run: |
        npx -p npm-check-updates ncu -u
        npm ci
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies-${{ github.run_id}}
          base: main
      

 
